services:
  db:
    build: .
    container_name: graphql-blog-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgresq
      - POSTGRES_DB=graphql-blog

